### ISSUE TITLE
Update docs, test and prepare for newer versions

### ISSUE THREAD

**Issue by JJ** [zoffixznet/perl6-IO-CatHandle-AutoLines#1]
While we're checking out raku-community-modules/perl6-LN#2

**Comment by JJ** [comment]
Well, with the latest change in Rakudo (reported [here](https://github.com/rakudo/rakudo/issues/3548)) $*ARGFILES is no longer a IO::CatHandle, but a IO::Handle. This module used the on-reset feature of that class for writing stuff before resetting. I wonder if that could be totally eliminated.
Another alternative would be to deal differently with $*ARGFILES when it's equal to $*IN.

**Comment by lizmat** [comment]
Basically, when `$*ARGFILES` is an `IO::Handle`, it is functionally equivalent to `does IO::CatHandle::AutoLines[:!reset]`, because it will have no reset actions because there will only ever be one file.  I've just did that change, and now this module tests ok again.

**Comment by JJ** [comment]
Right... The problem is the reset functionality, which I don't find that useful anyway, but taking it out needs some study, I guess.

**Comment by lizmat** [comment]
No, it's not taken out for `IO::CatHandle`, it's just not used for `IO::Handle`.  Which doesn't matter, because with a single file there would never be a "on-change" event anyway.

**Comment by lizmat** [comment]
Ok, took a bit of finagling, but I think that `IO::CatHandle::AutoLines` and `LN` are now functioning as expected, and ready for official release.  Or should I take care of them personally?

**Comment by JJ** [comment]
I'll be working on them momentarily, but feel free to release them if you
want.
